apiVersion: v2
name: beeax
description: A Helm chart to deploy BeeAX CRM (server + worker) with optional PostgreSQL and Redis dependencies.
type: application
version: 0.1.0
appVersion: "v1.14.0"
icon: https://raw.githubusercontent.com/beeax/beeax/2f25922f4cd5bd61e1427c57c4f8ea224e1d552c/packages/beeax-website/public/images/core/logo.svg
