export type {
  ActorMetadata as ActorField,
  AddressMetadata as AddressField,
  CurrencyMetadata as CurrencyField,
  EmailsMetadata as EmailsField,
  FullNameMetadata as FullNameField,
  LinksMetadata as LinksField,
  PhonesMetadata as PhonesField,
  RichTextMetadata as RichTextField,
} from 'beeax-shared/types';
