apiVersion: v1
kind: PersistentVolume
metadata:
  name: beeaxcrm-server-pv
  namespace: beeaxcrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
