apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beeaxcrm-docker-data-pvc
  namespace: beeaxcrm
spec:
  storageClassName: default
  volumeName: beeaxcrm-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
