apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beeaxcrm-db-pvc
  namespace: beeaxcrm
spec:
  storageClassName: default
  volumeName: beeaxcrm-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
